import {Question} from './question.model';

export class Module {
    /**
     * uid of the module generated by cloud firestore
     */
    uid: string;
    /**
     * description of the module
     */
    description: string;
    /**
     * name of the module
     */
    name: string;
    /**
     * searchable tags of the module
     */
    tags: string[];
    /**
     * questions contained by the module
     */
    questions: Question[];
    /**
     * calculated progress of the module
     * @see calcProgress
     */
    progress: number;
    /**
     * global playcount of the module used for recommendations
     */
    globalPlayCount: number;

    constructor(uid: string, description: string, name: string, tags: string[], globalPlayCount: number) {
        this.uid = uid;
        this.description = description;
        this.name = name;
        this.tags = tags;
        this.questions = [];
        this.progress = 0;
        this.globalPlayCount = globalPlayCount;
    }

    /**
     * calculates the progress of the module based on the progress of each question the module contains
     */
    calcProgress() {
        let result = 0;
        this.questions.forEach(question => result += question.progress);
        this.progress = Math.round(((result / Question.MAX_PROGRESS) / this.questions.length) * 100);
    }
}
